ml4ai/automates

text_reading/src/main/scala/org/clulab/aske/automates/entities/StringMatchEntityFinder.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestDefinitions.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestParameterSetting.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestVariables.scala

@bsharpataz, the only important changes are those in StringMatchEntityFinder.scala. I tried to fix that parsing error we had:
```
[info] - should extract variables from t1b: In APSIM, water uptake (Ta, mm d−1) is determined from potential transpiration demand (Tp, mm d−1), soil water available (WA, mm d−1), and water supply (WS, mm d−1) for each ith day and soil layer as: *** FAILED ***
[info]   org.clulab.odin.impl.OdinNamedCompileException: Error parsing rule 'stringmatch': Unmatched closing ')' near index 9
[info] Ta, mm d−1) is determined from potential transpiration demand (Tp, mm d−1
[info]          ^
[info]   at org.clulab.odin.impl.RuleReader.mkExtractor(RuleReader.scala:310)
[info]   at org.clulab.odin.impl.RuleReader.$anonfun$mkExtractors$4(RuleReader.scala:85)
[info]   at …
```

Regex spec char replacement

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/comments/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/comments/entities.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/comments/master.yml
text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
text_reading/src/test/resources/test.conf
text_reading/src/test/scala/org/clulab/aske/automates/TestUtils.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestCommentDefinitions.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestCommentVariables.scala

- went back on this change from the previous PR because it looks like that broke several tests:
https://github.com/ml4ai/automates/blob/4214b0dbf8078a4fbb78f9c38a3142b51bc201d8/text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala#L79
- made changes to have comment tests use CommentEngine and not TestEngine;
- wrote a rule to extract vars and definitions from comments---the var tests pass, but not definition ones although the mentions as printed out from within the comment definition tests seem to look right; haven't figured out why the tests fail yet (upd: found the error in the rule that caused the tests to break);
- changed the comment tests not to include 'is' (we don't insert 'is' in preprocessing, so neither the rules, nor the tests will contain it);
- added a todo …

Comment tests

---

pdfalign/pdfalign.py

This seems to address @adarshp's suggestion that @cl4yton mentioned in his email---by default, the boxes will be character-based for in-equation variables and token-based for everything else. Let me know if that doesn't work. 
Please still try to make sure to switch to characters in cases where the token-level box happens to include punctuation.

toggling boxes per annotation entity type

---

pdfalign/README.md
pdfalign/pdfalign.py
pdfalign/setup.py

This PR implements the following improvements:
- Adds tqdm progress bars to the terminal (for the impatient)
- Speeds up bounding box tree construction by pre-sorting by area (2x speedup for token boxes, 3.5x speedup for character boxes)
- pdfalign automatically jumps to the page containing the equation in the paper when it is opened.
- Buttons now have the associated keyboard shortcuts in their label.
- Previous page/next page button labels replaced with arrowheads.

Speed and ergonomics improvements in pdfalign

---

pdfalign/pdfalign.py

This PR does away with the need for the 'Show' button - the associated components are automatically shown when a saved annotation is selected.

Automatically showing components when a saved annotation is selected

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/parameterSettings.yml
text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestDefinitions.scala

- updates to sort_of_appos
- keepLongest is no longer applied to definition mentions---there could be multiple of those per variable (so there could be some overlap)
- a couple of minor fixes

Fixes  in response to GE feedback 

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities/grammar/avoid.yml
text_reading/src/main/scala/org/clulab/aske/automates/data/Preprocessor.scala
text_reading/webapp/app/controllers/HomeController.scala

1. Filter out ugly strings that result from pdfs having vertical text, e.g., 
2. Fix bug from previous PR---one of the methods in HomeController included reading sections from the pdf, and the sections key is now optional.

Vertical text + fixing the bug from previous PR

---

src/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
src/text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala
src/text_reading/src/main/scala/org/clulab/grounding/Grounder.scala

@BeckySharp, is this roughly what you had in mind? This adds a section to the link element that contains potential terms to query svo for for this text variable, e.g.:
```
"element_1": {
"source": "/Users/phein/Google Drive/ASKE-AutoMATES/Data/Mini-SPAM/docs/SPAM/PET/petpt_2012.pdf_sent72_Interval(0, 6)",
"content_type": "null",
"svo_query_terms": ["index", "area_index", "Leaf_area_index"],
"content": "LAI",
"type": "text_var"
}
```
@pauldhein, would you be able to query svo with those terms there?

svo query terms added to text_var link element

---

src/text_reading/src/main/scala/org/clulab/grounding/Grounder.scala

- filtering out non-letter characters from svo query terms other than underscores and dashes---should fix the svo query error 400; 
- in getCompounds, disallowing words to have non-letter characters---fixes the Priestley_-_Taylor incorrect compound---dash was found as a separate words by the tokenizer

svo error 400

---

docs/software.md
src/equation_reading/equation_extraction/README.md

This PR includes some simple path changes to fix the equation extraction documentation links on [the AutoMATES webpage](https://ml4ai.github.io/automates/software/). Closes #143 .

Fixing paths in equation documentation

---

scripts/equation_reading/mathjax/webservice/server.js

I added a catch that outputs failure cases of LaTeX --> MathML conversion. The equation that failed and the cause of failure are outputted as opposed to the translated MathML when a MathJax promise fails. our code now processes all equations regardless of failures.

MathJax conversion promise graceful failure

---

README.md

- Our UA addendum to the Apache 2.0 License is not recognizable by GitHub so I am removing the shield icon
- Our repository CodeFactor score is now displayed on the README. It's time to improve our score!

README Shields Update

---

Dockerfile

Simple PR that adds the TR dependencies into our AutoMATES Docker image. This is done to improve CI testing speed.

Caching TR Dependencies

---

automates/text_reading/src/main/resources/application.conf
automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities.yml
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/actions/ExpansionHandler.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/TestUtils.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestDefinitions.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestFunctions.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestVariables.scala

Fixed a few tests and broke a few (the broken ones had to be broken to address more crucial issues)
Major-ish changes:
- construct new defs instead of copying with new args while untangling conjunctions (needed because the full mention token interval changes and also this way we can update `foundBy` with the information about using the untangle conj action)
- some new methods for filtering overlapping mentions 
- updates to the `untangleConj` action

You win some, you lose some

---

automates/text_reading/src/main/resources/application.conf

(Re-opening with fix commit history)
Hello @maxaalexeeva , @pauldhein was helping me set up the TR web app on machine so I can do some work on model assembly. We were encountering an issue where the TR app could not locate the vectors.txt file on certain API calls. The change in the apps configuration show in this pull request resolved the issue. Please review and let me know if the change works!

Text Reading web app configuration fix

---

automates/text_reading/src/main/resources/application.conf
automates/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndExport.scala

@alicekwak 
if you run the ExtractAndExport app (the one I modified; use intellij or you can do it with `sbt run` and then enter the number for ExtractAndExport app, should be 4?), it will output a tsv file with some useful information (doc name, sentence, mention label and type + all args with text for that mention). Types of output (in this case .tsv) are defined in exportAs in application.conf. We normally use the json, but this tsv is more usuful for manual analysis.

adjusting extract and export to use cosmos loader and updating what prints to tsv

---

automates/apps/automates/automates.py
automates/apps/automates/execute_driver.py
automates/apps/automates/model_code/chime_sir.py
automates/apps/automates/model_code/sir_simple.py
tests/apps/automates/execution/test_gromet_experiment_execution.py

Adds an endpoint to the automates app that mimics execution of a grommet experiment. It allows a user to give inputs and select outputs for CHIME-SIR and SIR-Simple grommets. 
When a particular gromet model is selected, the endpoint actually runs the python source code the gromet is generated from and returns the result.

Add mocked gromet experiment execution endpoint

---

automates/program_analysis/CAST2GrFN/visitors/cast_to_token_cast_visitor.py

Small changes to the CAST to token CAST visitor so that  the token CAST has spacing around the parentheses.
In other words, fixed it so it goes from
(fn1 arg1 (fn2 arg2 arg3)) to
( fn1 arg1 ( fn2 arg2 arg3 ) )

Added spacing around parentheses, for easier tokenization.

---

automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/actions/ExpansionHandler.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/serializer/AutomatesSerializer.scala
automates/text_reading/src/main/scala/org/clulab/utils/AlignmentUtils.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/alignment/TestAlign.scala

main change: drop Identifier label on an expanded Identifier mention---it is no longer just an identifier if we expand---this was what broke test t3f
other:
- added det to invalid outgoing to one of new invalid outgoings---it was expanding to just the determiner;
- set hops back to five; 
- remove 'foundBy' in toAttachment---key was not found because foundBy does not occur in all types of attachments, which broke align test

Debugging test t3f

---

automates/program_analysis/GCC2GrFN/gcc_basic_blocks_to_digraph.py

Added code to convert the basic blocks obtained from the gcc AST json to a networkx digraph.  Nodes are represented by a data class `BBNode` which currently has one member variable `index`.  Edges are built into the graph following the `edges` field of the basic block json, and each edge in the digraph contains an `EdgeData` object which includes the edges gcc flags and human readable type obtained from the flags.  The main functionality is provided by the function `basic_blocks_to_digraph()` which takes a list of basic blocks e.g. the basic blocks of a function and returns the digraph representing the flow of control between these basic blocks.
- Added `gcc_basic_blocks_to_digraph.py`  which adds a namedtuple `BBNode` to store node data in the digraph, and a namedtuple `EdgeData` to …

[PA]: gcc AST basic blocks to networkx digraph

---

automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/taxonomy.yml
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestParameterSetting.scala

- remove param setting mentions if there are more complete, overlapping interval param settings 
- disallow ParamAndUnit mentions that have more than one identifier (each mention should be associated with only one identifier)
- added a copyWithFoundBy method (for easier labeling of mentions with actions involved in their creation), e.g., here, the mention has been produced by the `var-word-equals_value-token` and the `assembleVarsWithParamsAndUnits` action:
```
List(ParamAndUnit, Event) => refugee move speed is equal to 200 
------------------------------ 
Rule => var-word-equals_value-token++assembleVarsWithParamsAndUnits 
Type => RelationMention 
------------------------------ 
value (Value, Measurement, Phrase, Entity) => 200 
unit (Unit, Measurement, Phrase, Entity) => km per day …
```

Unit and param men fix dec2021

---

automates/model_assembly/metadata.py

Added a small check in metadata.py that checks whether the input GrFN has no code_span metadata information. This is to allow GrFNs to be executed on the web API and to have their expression trees extracted in the case they have no code_span information.

Null code_span metadata GrFN generation

---

automates/model_assembly/metadata.py
automates/model_assembly/networks.py
automates/program_analysis/CAST2GrFN/ann_cast/annotated_cast.py
automates/program_analysis/CAST2GrFN/ann_cast/grfn_var_creation_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/to_grfn_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/variable_version_pass.py

- Added metadata for variables introduced for interfaces, return values, arguments, and conditionals
- After adding metadata, we adjusted aliasing of GrFN variables.
- Fixed bug with FunctionDef argument ids in top interface.  This resolves an issue for GrFN generation for 3.0 FunctionDef containers

Added FromSource metadata to GrFN, fixed 3.0 FunctionDef containers 

---

automates/model_assembly/metadata.py
automates/model_assembly/networks.py
automates/program_analysis/CAST2GrFN/ann_cast/annotated_cast.py
automates/program_analysis/CAST2GrFN/ann_cast/container_scope_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/grfn_var_creation_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/lambda_expression_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/to_grfn_pass.py
automates/program_analysis/CAST2GrFN/ann_cast/variable_version_pass.py
scripts/program_analysis/gcc_to_agraph.py

- Implemented a flag `FROM_SOURCE_FOR_GE` which will change the from source metadata for VariableNodes to be as they requested
- Specialized globals are now used for 2.3 FunctionDefs
- Resolved a GrFN generation issue with Interface nodes that are neither grandparents nor have a grandparent
- Added variable ids to variables in lambda expressions to fix an issue with variable name collisions
- Changed loop container's top interface to be of type `LoopTopInterface`.  This will be helpful later during execution implementation
- Added in dummy assignments to FunctionDef's when those variables are expected to propagate through a container's top interface.  This resolves issues for CAST generated from Python due to dynamic variable creation e.g.
```python
def func():
z = 3
if z == 3:
y = 5 …
```

AnnCast-To-GrFN: Updates for 2.3 FunctionDefs/Calls and General Fixes

---

automates/program_analysis/CAST2GrFN/ann_cast/to_gromet_pass.py

This PR addresses a discrepancy brought on by adding support for Bucky Model generation.
The issue is as follows
- Missing wiring related to loops in CHIME_SIR and CHIME_SVIIvR models.
The issue has been addressed in addition to the following issues:
- Incorrect metadata generation for some ports
- Incorrect GroMEt FNs for "get" and "set" primitives.

CHIME Gromet Wiring Fix PR
