ml4ai/automates

text_reading/src/main/scala/org/clulab/aske/automates/apps/ParsePdfsToJson.scala
text_reading/src/main/scala/org/clulab/aske/automates/scienceparse/ScienceParseClient.scala
text_reading/src/main/scala/org/clulab/aske/automates/scienceparse/ScienceParseDocument.scala

fyi @maxaalexeeva 
added methods to use the scienceparse client as a pre-processing step, added app to read pdfs and store as json files
the client may be a little finicky, of the few times I tried running the app, once it timed out and so failed, other times it worked like a charm..... fyi @marcovzla

Entrypoints

---

text_reading/build.sbt
text_reading/input/input1.txt
text_reading/src/main/resources/automates.conf
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndExport.scala

add JSONExporter for Extract and Export

---

documentation/reports/m3_report_prototype_system/machine_reading.md
documentation/reports/m3_report_prototype_system/model_analysis.md

Hi @marcovzla @bsharpataz @pauldhein ,
Just FYI - I have made slight modifications to the image inclusion markup to make it work with the automatic PDF report generation.

Updating image inclusion markup to work with PDF generation

---

equation_extraction/collect_data.py

check several scale factors to best match equation template

---

documentation/reports/build_report.py
documentation/reports/m3_report_prototype_system/code_summarization.md
documentation/reports/m3_report_prototype_system/equations.md
documentation/reports/m3_report_prototype_system/for2py.md
documentation/reports/m3_report_prototype_system/index.md
documentation/reports/m3_report_prototype_system/machine_reading.md
documentation/reports/m3_report_prototype_system/model_analysis.md
documentation/reports/m3_report_prototype_system/webapp.md
documentation/reports/pandoc_report_template.tex

This PR implements minor edits to the monthly report.
It also modifies the PDF building script to produce an intermediate .tex file that can be inspected and modified if manual tuning/adjustment is required for the final PDF version of the report (FYI @cl4yton )

Minor edits to report

---

equation_extraction/collect_data.py
equation_extraction/latex.py

Macro expansion!

---

text_reading/src/main/resources/automates.conf
text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/master.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/master_variables.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/taxonomy.yml
text_reading/src/main/resources/reference.conf
text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
text_reading/src/main/scala/org/clulab/aske/automates/actions/ExpansionHandler.scala
text_reading/src/main/scala/org/clulab/aske/automates/entities/StringMatchEntityFinder.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestVariables.scala

@zupon fyi
@maxaalexeeva please check over and let me know if you think this is a good idea -- we can use all, some, or none of it :)

Becky tests

---

equation_extraction/expand_arxiv.py

Docker fix

---

text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndExport.scala
text_reading/src/test/scala/org/clulab/aske/automates/TestUtils.scala
text_reading/webapp/app/controllers/HomeController.scala

fyi @maxaalexeeva @zupon @marcovzla

Fromconfig

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities/grammar/avoid.yml
text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala

changes Masha and I made in the past ~2 days

Fixing defs

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities/grammar/avoid.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities/grammar/entities.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/parameterSettings.yml

added a rule to find intervals; 
added an avoid to help find intervals; 
edited rules for more_than and less_than (the token versions are still there for my reference);
added a rule for mislabeled adj for future use(commented out for now)

Finding param settings (intervals and more/less than)

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/parameterSettings.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/unused/unused_rules.yml

moved currently not used rules (but that we might need in future) to unused/unused_rules.yml; 
adjusted entity rules

minor rule clean-up

---

code_summarization/src/generation.py
code_summarization/src/scripts/build_generation_dataset.py
code_summarization/src/scripts/max_code_length.py
code_summarization/src/utils/bleu.py
code_summarization/src/utils/generators.py
code_summarization/src/utils/utils.py

Added a generation model and dataset based upon our updated corpus and code/docstring representation.

Code summarization generation model

---

text_reading/src/main/scala/org/clulab/aske/automates/actions/ExpansionHandler.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala

corrected previous pr

---

equation_extraction/collect_data.py
equation_extraction/run_data_collection.sh

context tokens file and the cropped equation image file

New dataset collection modifications

---

text_reading/webapp/app/views/index.scala.html

Now just under the brat extraction viz

moved syntax up a bit in webapp

---

text_reading/input/SIR/grfn/SIR-Gillespie-SD_GrFN.json
text_reading/src/main/resources/automates.conf
text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
text_reading/src/main/scala/org/clulab/aske/automates/data/DataLoader.scala

- added the sir grfn json (the ideal sir model json was already in master: https://github.com/ml4ai/automates/blob/master/text_reading/input/SIR/text/ideal_sir_model.json)
- Becky added the code for reading the new grfn json
- made some updates to rules
- added the text of the abstract to the sections so that we get mentions from the abstract too
- changed the number of topK results returned to 3
- changed the outputDirectory name to just 'output' instead of 'output/SIR'

Reading new json with becky

---

text_reading/build.sbt
text_reading/input/equations/sir_ideal_downsampledModel/input/predictions.txt
text_reading/src/main/resources/automates.conf
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
text_reading/src/main/scala/org/clulab/aske/automates/data/DataLoader.scala
text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala

FYI -- idk if we want to PR it in... thoughts?

Added equation chunking and temp alignment to txt spans

---

text_reading/src/main/resources/automates.conf
text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
text_reading/src/test/resources/test.conf

@BeckySharp, I have added the code to read the comments from grfn instead of txt, but let's merge your PR first and then I'll resolve whatever conflicts arise? (and whatever other comments you may have for this)

Reading comments from json

---

pdfalign/README.md
pdfalign/pdfalign.py

This PR implements updates to pdfalign so that it uses ttk widgets for a more native look and feel.

Switching to ttk widgets in pdfalign

---

pdfalign/README.md
pdfalign/pdfalign.py
pdfalign/setup.py

This small PR adds a keyboard shortcut (`k`) to toggle token boxes.

Making pdfalign a pip-installable package, adding keyboard shortcut to toggle boxes, documentation updates

---

pdfalign/pdfalign.py

This PR adds a shortcut, 'n' for starting a new annotation. It also changes the label of the 'New annotation' button to read 'Annotate new variable'.

New annotation shortcut

---

text_reading/src/main/resources/org/clulab/aske_automates/grammars/definitions.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/entities/grammar/entities.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/master.yml
text_reading/src/main/resources/org/clulab/aske_automates/grammars/unitRels.yml
text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
text_reading/src/main/scala/org/clulab/aske/automates/actions/ExpansionHandler.scala
text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
text_reading/src/main/scala/org/clulab/aske/automates/entities/StringMatchEntityFinder.scala
text_reading/src/main/scala/org/clulab/aske/automates/grfn/GrFNParser.scala
text_reading/src/test/scala/org/clulab/aske/automates/entities/TestStringMatchEntityFinder.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestDefinitions.scala
text_reading/src/test/scala/org/clulab/aske/automates/text/TestParameterSetting.scala

plus whatever else the commit messages say.
Some tests broke, but I think the output overall is better. Will look at the broken tests later (ignored for now).
@pauldhein, let me know if this works for you now.

Reading from different comment formats + rule adjustments

---

code_summarization/src/main.py
code_summarization/src/scripts/build_classification_datasets.py
code_summarization/src/scripts/character_data.py
code_summarization/src/utils/classfiers.py
code_summarization/src/utils/utils.py

Just merging this old code that I had finished for code summarization but never added to master.

Old work on code summarization

---

.travis.yml
Dockerfile

This PR fixes the Travis tests through an update to the AutoMATES Dockerfile.

Travis fixes and updated dockerfile

---

Dockerfile

Changing the location of the requirements script for building the docker image on docker-hub

Improving dockerfile

---

tests/Dockerfile

This PR adds git credentials to our docker testing image

Avoid Git checkout issues in Docker

---

scripts/model_analysis/grfn_links_to_csv.py
scripts/text_reading/alignment2link_graph.py
scripts/text_reading/extract_align_ground.py
src/model_analysis/linking.py
tests/data/model_analysis/PEN-alignment.json
tests/model_analysis/test_GrFN.py
tests/model_analysis/test_linking.py

- re-organized the link graph creation using custom-made node classes.
- Link graph is now a DiGraph with directional arrows that ensure source variables are at the root of grounding graph trees
- Now outputting a grounding graph view where nodes are ranked according to content type
- Link tables have been updated to work with new data types

Updating link table viewer

---

automates/equation_reading/equation_translation/eqdec/readme.txt
scripts/equation_reading/README.md
scripts/equation_reading/batch_decode_eq_images.py
scripts/equation_reading/render_eq_img_from_latex.py

Updates eqdec readme.txt with directions about model file location and execution directory context.
Adds CHIME model documentation paths to eqn processing scripts.
Ready for review and merge, followed by delete

Eqn clay 2

---

scripts/program_analysis/ast_explorer.py

Some simple updates to the Python AST walker that I made in support of analyzing the PID code from GE for the ReMath proposal effort. These updates enhance our parsing abilities when printing a Python AST as a CAST and add some improvements to the output graph visualization.

PyAST Walker Updates

---

automates/text_reading/src/main/resources/application.conf
automates/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala

Added a variable to the config file to store the project's root directory path.
All other path's should be relative to this.

added project root to config

---

.gitignore
README.md
environment.yml

Adding updates to our gitignore and README. Including a new `conda` environment creation file.

Repo updates

---

automates/model_assembly/networks.py
automates/model_assembly/structures.py
scripts/model_assembly/grfn_json_to_cag.py

- A few conditional checks for field names in GrFN/CAG JSONs
- Pretty-printing of variable node names in GrFN/CAG PDFs

Model Assembly Updates to handle CovidActNow

---

automates/model_analysis/sensitivity.py
automates/model_assembly/networks.py
scripts/model_analysis/simple_sir_sa.py
tests/model_analysis/test_visualization.py

- Extended our sensitivity analysis methods to work with GrFNs that have multiple outputs

Sensitivity Analysis Over Multi-output GrFNs

---

automates/model_analysis/sensitivity.py
automates/model_assembly/networks.py
automates/model_assembly/sandbox.py
automates/model_assembly/structures.py
automates/program_analysis/translators/for2py/genPGM.py
tests/data/model_analysis/PT_GrFN.json
tests/data/program_analysis/grfn_execution/basic_assignment_grfn.json
tests/data/program_analysis/grfn_execution/grfn_with_types.json
tests/data/program_analysis/grfn_execution/loop_grfn.json
tests/model_assembly/test_interpreter.py
tests/program_analysis/test_grfn_execution.py

Change GrFN execution to traverse the tree of subgraphs during execution

GrFN Execution Updates

---

automates/model_assembly/networks.py
tests/program_analysis/test_grfn_execution.py

- Enables execution using NumPy for batches of inputs
- Vectorized execution works with loops, variable loops, and user defined types

GrFN vectorized execution

---

Dockerfile

Update Automates Dockerfile to include GCC build for GCC Plugin Testing

Update Automates Dockerfile to include GCC

---

automates/program_analysis/CAST2GrFN/cast.py
automates/program_analysis/CAST2GrFN/visitors/cast_to_agraph_visitor.py
scripts/program_analysis/cast_to_agraph.py
tests/data/program_analysis/CAST2PDF/cast_all_nodes.json
tests/program_analysis/test_cast_to_pdf.py

The 'ghost test' is a file I found in CAST2GrFN's tests called 'cast_all_nodes.json' which looks to have a good deal of the CAST nodes in the file. I think this is good enough to solve the coverage issues, but let me know and I could come up with something else. I wrote a test script that reads the JSON file, creates a pdf out of it, and then deletes the pdf. Then, the test passes by default.

Adding 'ghost test' for cast_to_pdf

---

automates/model_assembly/networks.py

Removing print statements from GrFN execution

---

automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/taxonomy.yml
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala

adjustments to the filterFunction method (checking if there is an identifier before filtering on identifier label); modified taxonomy to include measurements as a phrase subtype

filter function fix

---

automates/text_reading/README.md
automates/text_reading/shell
automates/text_reading/src/main/scala/org/clulab/aske/automates/apps/AutomatesShell.scala
automates/text_reading/src/main/scala/org/clulab/utils/DisplayUtils.scala

ported a very basic shell from reach---from the first commit, not the current one.

Basic shell

---

.github/workflows/ci.yaml

Adding proper container/image removal during CI testing phase.

Fixing container/image removal bug

---

automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinEngine.scala
automates/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAlign.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/TestUtils.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestAttachments.scala

- fixed a bug in untangle conj (attachments should not be empty - that was not the case when those were originally written)
- deleted unused code
- added attachments tests

Overlapping description fix

---

automates/model_assembly/air.py
automates/model_assembly/interfaces.py
automates/model_assembly/linking.py
automates/model_assembly/metadata.py
automates/model_assembly/networks.py
automates/model_assembly/text_reading_linker.py
scripts/model_assembly/SIR-simple--alignment.json
tests/data/example-tr-data/chime-sir/CHIME-SIR--alignment.json
tests/data/example-tr-data/chime-sir/CHIME-SIR--mentions.json
tests/data/example-tr-data/sir-simple-documents/SIR-simple--alignment.json

Linking the unit metadata to the TR alignment
Updated the code to handle the global source and global comment span alignment information.

Linking TR alignment to unit metadata pull request

---

automates/apps/automates/execute_driver.py
automates/apps/automates/model_code/chime_sviivr.py

Adding support to execute CHIMESVIIvR.py through the automates 'web app'

Ferra/chimesvir rest app CHIMESVIIvR execution endpoint PR

---

automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/functions.yml
automates/text_reading/src/main/resources/org/clulab/aske_automates/grammars/vars.yml
automates/text_reading/src/main/scala/org/clulab/aske/automates/OdinActions.scala
automates/text_reading/src/test/scala/org/clulab/aske/automates/text/TestFunctions.scala

- Added a few function rules to cover more patterns found from CHIME / SIR models
- Revised a function arg filter to capture wrongly excluded cases (i.e. inputs / outputs with gerunds)

Quick addition/revision to function rules

---

scripts/gromet/gromet_metadata_enrichment.py
scripts/gromet/gromet_variable_enrichment.py

* Add a script to add variable objects into a gromet given its ports and wires
* Add a script to add metadata into gromet variables given its matching grfn3 with metadata in it

Add GroMEt update scripts

---

scripts/ghidra/DumpRefined.py
scripts/ghidra/DumpUnrefined.py
scripts/ghidra/README.md

Add two python Ghidra scripts into the code base that allow us to dump the P Code for a binary.

Add Ghidra scripts

---

automates/program_analysis/CAST2GrFN/ann_cast/to_gromet_pass.py

Pull Request to merge in changes that add support for Unary Subtraction (USub) GroMEt generation.
Also fixes a minor bug with creating pofs when it comes to Binary Operations.

GroMEt USub Pull Request

---

automates/program_analysis/CAST2GrFN/ann_cast/to_gromet_pass.py
automates/program_analysis/CAST2GrFN/visitors/cast_to_agraph_visitor.py
automates/program_analysis/PyAST2CAST/py_ast_to_cast.py

Adds initial support for GroMEt dictionary generation:
In particular:
- Generating CAST Dictionary LiteralValue 
- Visualization for Dictionaries
- Generating a GroMEt dictionary literal
- Generating _get and _set calls for dictionaries.
One change that was done was to the '_List_get' and '_List_set' functions. They're currently changed to be type-general, in other words they're generic '_get' and '_set'. In the future this will probably change to be more type-specific.

GroMEt Dictionaries PR

---

automates/text_reading/src/main/scala/org/clulab/aske/automates/apps/ExtractAndAssembleMentionEvents.scala
scripts/model_assembly/cosmos_integration.py

Fixed a couple bugs that crashed the TR apps when certain filename assumptions weren't met

Code robustness fixes to TextReading scripts
